[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "deploygent"
version = "0.1.7"
description = "Deploy AI agents effortlessly."
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn",
    "click",
    "pydantic"
]

[project.scripts]
deploygent = "deploygent.cli:cli"